### ISSUE TITLE
Get balance should accept `sk`

### ISSUE THREAD

**Issue by joshuef** [maidsafe/safe_client_libs#853] opened 2019-06-17 15:32 UTC
Getting a `CoinBalance` balance, should be an `ownedGet`. So a `sk` must be passed. 

Currently, no `sk` is accepted by `get_balance`: `fn get_balance(&self, destination: XorName) -> Box<CoreFuture<Coins>>` (https://github.com/maidsafe/safe_client_libs/blob/experimental/safe_core/src/client/mod.rs#L299)

Wanted: Ability to get balance from arbitrary coin balance

**Comment by lionel1704** [comment] 2019-06-18 07:09
Similar to #843

**Comment by lionel1704** [comment] 2019-06-24 10:52
Duplicate of #843

**Closed by lionel1704** 2019-06-24 10:52 UTC
Labels: duplicate, for_safe_cli
